[package]
name = "rewind-cng"
version = "0.1.0"
authors = ["Damien Aumaitre <daumaitre@quarkslab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rewind-cli = { path = "../../rewind-cli" }
anyhow = "1.0.35"
rand = { version = "0.8.3", features = ["std"] }
color-eyre = "0.5.11"
