[package]
name = "cng"
version = "0.1.0"
authors = ["Damien Aumaitre <daumaitre@quarkslab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["fileapi", "winnt", "handleapi", "ioapiset", "errhandlingapi"] }
clap = { git = "https://github.com/clap-rs/clap/" }
anyhow = "1.0.34"
thiserror = "1.0.22"
color-eyre = "0.5.8"
eyre = "0.6.3"
